#if !defined(INCLUDE_ARRAY_MACROS_IB_IBFX_H)
#define INCLUDE_ARRAY_MACROS_IB_IBFX_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1], [0 : ksize+1]
#define IBFX(I, J, K) (ibfx[(I-1) + (isize+0) * ((J  ) + (jsize+2) * (K  ))])
#define IBFX_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_IB_IBFX_H
