#if !defined(INCLUDE_ARRAY_MACROS_IB_IBFY_H)
#define INCLUDE_ARRAY_MACROS_IB_IBFY_H

// This file is generated by tools/define_arrays.py

// [1 : isize+0], [0 : jsize+1]
#define IBFY(I, J) (ibfy[(I-1) + (isize+0) * (J  )])
#define IBFY_NADDS (int [NDIMS][2]){ {0, 0}, {1, 1}, }

#endif // INCLUDE_ARRAY_MACROS_IB_IBFY_H
