# define macros to access arrays easily
# for 1D, x-face, x-center, their distances are defined
# for ND, UX-like, UY-like, UZ-like, and P-like arrays are defined

import sys
import enum
import re


debug = False

def attach_header(f, name, with_domain_h):
    # write header part (include guard)
    name = name.upper()
    f.write(f"#if !defined(ARRAYS_{name}_H)\n")
    f.write(f"#define ARRAYS_{name}_H\n")
    f.write("\n")
    f.write("/* This file is automatically generated by define_array.py */\n")
    f.write("\n")
    f.write("// check NDIMS (number of spatial dimensions)\n")
    f.write("#if !defined(NDIMS)\n")
    f.write("#error \"define NDIMS: -DNDIMS=2 or -DNDIMS=3\"\n")
    f.write("#endif\n")
    f.write("\n")
    if with_domain_h:
        f.write("#include \"domain.h\"\n")
        f.write("\n")

def attach_footer(f, name):
    # close macro started by attach_header
    name = name.upper()
    f.write("#endif // ARRAYS_{name}_H\n")

class VectorType(enum.Enum):
    XFACE   = enum.auto()
    XCENTER = enum.auto()

def generate_grid_1d(f, name, vector_type):
    # prepare macros for one-dimensional vector
    # Four types are defined, [xy]-[face/center]
    name = name.strip()
    uname = name.upper()
    if vector_type == VectorType.XFACE:
        lbound = "1"
        ubound = "isize+1"
        size = "isize+1"
        index = "N-1"
    elif vector_type == VectorType.XCENTER:
        lbound = "0"
        ubound = "isize+1"
        size = "isize+2"
        index = "N"
    else:
        print("unknown vector type:", vector_type)
        return
    format_dict = {
            "name": name,
            "uname": uname,
            "lbound": lbound,
            "ubound": ubound,
            "size": size,
            "index": index,
    }
    string = (
            "/* {name} (double, 1D) [{lbound}:{ubound}] */\n"
            "#define {uname}_SIZE ({size})\n"
            "#define {uname}(N) ({name}[{index}])\n"
            "\n"
    )
    string = string.format(**format_dict)
    f.write(string)

class ArrayType(enum.Enum):
    UX_LIKE = enum.auto()
    UY_LIKE = enum.auto()
    UZ_LIKE = enum.auto()
    P_LIKE  = enum.auto()

def get_index_2d(uname, xs, ys):
    if xs == "0":
        ipart = "(I  )"
    elif int(xs) > 0:
        ipart = "(I-{:d})".format(+int(xs))
    elif int(xs) < 0:
        ipart = "(I+{:d})".format(-int(xs))
    else:
        print("xs:", xs)
        print("To Be Implemented")
        sys.exit()
    if ys == "0":
        jpart = "(J  )"
    elif int(ys) > 0:
        jpart = "(J-{:d})".format(+int(ys))
    elif int(ys) < 0:
        jpart = "(J+{:d})".format(-int(ys))
    else:
        print("ys:", ys)
        print("To Be Implemented")
        sys.exit()
    return f"{jpart} * {uname}_SIZE_0 + {ipart}"

def get_index_3d(uname, xs, ys, zs):
    if xs == "0":
        ipart = "(I  )"
    elif int(xs) > 0:
        ipart = "(I-{:d})".format(+int(xs))
    elif int(xs) < 0:
        ipart = "(I+{:d})".format(-int(xs))
    else:
        print("xs:", xs)
        print("To Be Implemented")
        sys.exit()
    if ys == "0":
        jpart = "(J  )"
    elif int(ys) > 0:
        jpart = "(J-{:d})".format(+int(ys))
    elif int(ys) < 0:
        jpart = "(J+{:d})".format(-int(ys))
    else:
        print("ys:", ys)
        print("To Be Implemented")
        sys.exit()
    if zs == "0":
        kpart = "(K  )"
    elif int(zs) > 0:
        kpart = "(K-{:d})".format(+int(zs))
    elif int(zs) < 0:
        kpart = "(K+{:d})".format(-int(zs))
    else:
        print("zs:", zs)
        print("To Be Implemented")
        sys.exit()
    return f"{kpart} * {uname}_SIZE_1 * {uname}_SIZE_0 + {jpart} * {uname}_SIZE_0 + {ipart}"

def get_size(s, e):
    if debug:
        print("get_size, s and e:", s, e)
    # extract numbers
    s_ = re.sub("[a-zA-Z]", "", s)
    e_ = re.sub("[a-zA-Z]", "", e)
    # extract prefix
    string = re.sub("[0-9+-]", "", e)
    s_ = int(s_)
    if e_ == "":
        e_ = 0
    else:
        e_ = int(e_)
    size = "({}{:+d})".format(string, e_ - s_ + 1)
    if debug:
        print("get_size, size:", size)
    return size

def generate_grid_nd(f, name, xs, xe, ys, ye, zs, ze):
    name = name.strip()
    uname = name.upper()
    index_2d = get_index_2d(uname, xs, ys)
    index_3d = get_index_3d(uname, xs, ys, zs)
    size0 = get_size(xs, xe)
    size1 = get_size(ys, ye)
    size2 = get_size(zs, ze)
    format_dict = {
            "name": name,
            "uname": uname,
            "index_2d": index_2d,
            "index_3d": index_3d,
            "size0": size0,
            "size1": size1,
            "size2": size2,
    }
    string = list()
    # header
    string.append((
            "/*** {name} ***/\n"
    ))
    # 2D array (not for z-related things)
    if not "z" in name:
        string.append((
            "#if NDIMS == 2\n"
            "#define {uname}_SIZE_0 {size0}\n"
            "#define {uname}_SIZE_1 {size1}\n"
            "#define {uname}(I, J) ({name}[ {index_2d} ])\n"
            "#endif // NDIMS == 2\n"
        ))
    # 3D array
    string.append((
            "#if NDIMS == 3\n"
            "#define {uname}_SIZE_0 {size0}\n"
            "#define {uname}_SIZE_1 {size1}\n"
            "#define {uname}_SIZE_2 {size2}\n"
            "#define {uname}(I, J, K) ({name}[ {index_3d} ])\n"
            "#endif // NDIMS == 3\n"
    ))
    # footer
    string.append((
            "/*** {name} ***/\n\n"
    ))
    string = "".join(string)
    string = string.format(**format_dict)
    f.write(string)

if __name__ == "__main__":
    # coordinates in wall-normal direction
    with open("domain.h", "w", encoding="utf-8") as f:
        attach_header(f, "domain", False)
        generate_grid_1d(f, "xf",  VectorType.XFACE  )
        generate_grid_1d(f, "xc",  VectorType.XCENTER)
        generate_grid_1d(f, "dxf", VectorType.XFACE  )
        generate_grid_1d(f, "dxc", VectorType.XCENTER)
        attach_footer(f, "domain")
    # velocity, pressure, scalar potential, and source terms of RK
    with open("fluid.h", "w", encoding="utf-8") as f:
        attach_header(f, "fluid", True)
        generate_grid_nd(f, "ux",     "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uy",     "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uz",     "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "p",      "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "psi",    "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuxa", "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuxb", "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuxg", "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuya", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuyb", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuyg", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuza", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuzb", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srcuzg", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        attach_footer(f, "fluid")
    # temperature, thermal forcing, and souece terms of RK
    with open("temperature.h", "w", encoding="utf-8") as f:
        attach_header(f, "temperature", True)
        generate_grid_nd(f, "temp",       "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "tempforcex", "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srctempa",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srctempb",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "srctempg",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        attach_footer(f, "temperature")
    # immersed boundary, momentum exchange
    with open("ib.h", "w", encoding="utf-8") as f:
        attach_header(f, "ib", True)
        generate_grid_nd(f, "dux", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "duy", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "duz", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        attach_footer(f, "ib")
    # arrays to store temporally-averaged statistics
    with open("statistics.h", "w", encoding="utf-8") as f:
        attach_header(f, "statistics", True)
        # arrays have halo cells, which are not necessary
        # this is to simplify the output procedure (to use the same wrapper as velocity / temperature)
        generate_grid_nd(f, "ux1",   "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "ux2",   "1", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uy1",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uy2",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uz1",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "uz2",   "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "temp1", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        generate_grid_nd(f, "temp2", "0", "isize+1", "0", "jsize+1", "0", "ksize+1")
        attach_footer(f, "statistics")

