#if !defined(ARRAYS_DOMAIN_H)
#define ARRAYS_DOMAIN_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

/* xf (double, 1D) [1:isize+1] */
#define XF_SIZE (isize+1)
#define XF(N) (xf[N-1])

/* xc (double, 1D) [0:isize+1] */
#define XC_SIZE (isize+2)
#define XC(N) (xc[N])

/* dxf (double, 1D) [1:isize+1] */
#define DXF_SIZE (isize+1)
#define DXF(N) (dxf[N-1])

/* dxc (double, 1D) [0:isize+1] */
#define DXC_SIZE (isize+2)
#define DXC(N) (dxc[N])

#endif // ARRAYS_{name}_H
