#if !defined(ARRAYS_FLUID_H)
#define ARRAYS_FLUID_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** ux ***/
#define UX_SIZE_0 (isize+1)
#define UX_SIZE_1 (jsize+2)
#define UX(I, J) (ux[ (J  ) * UX_SIZE_0 + (I-1) ])
/*** ux ***/

/*** uy ***/
#define UY_SIZE_0 (isize+2)
#define UY_SIZE_1 (jsize+2)
#define UY(I, J) (uy[ (J  ) * UY_SIZE_0 + (I  ) ])
/*** uy ***/

/*** uz ***/
/*** uz ***/

/*** p ***/
#define P_SIZE_0 (isize+2)
#define P_SIZE_1 (jsize+2)
#define P(I, J) (p[ (J  ) * P_SIZE_0 + (I  ) ])
/*** p ***/

/*** psi ***/
#define PSI_SIZE_0 (isize+2)
#define PSI_SIZE_1 (jsize+2)
#define PSI(I, J) (psi[ (J  ) * PSI_SIZE_0 + (I  ) ])
/*** psi ***/

/*** srcuxa ***/
#define SRCUXA_SIZE_0 (isize+1)
#define SRCUXA_SIZE_1 (jsize+2)
#define SRCUXA(I, J) (srcuxa[ (J  ) * SRCUXA_SIZE_0 + (I-1) ])
/*** srcuxa ***/

/*** srcuxb ***/
#define SRCUXB_SIZE_0 (isize+1)
#define SRCUXB_SIZE_1 (jsize+2)
#define SRCUXB(I, J) (srcuxb[ (J  ) * SRCUXB_SIZE_0 + (I-1) ])
/*** srcuxb ***/

/*** srcuxg ***/
#define SRCUXG_SIZE_0 (isize+1)
#define SRCUXG_SIZE_1 (jsize+2)
#define SRCUXG(I, J) (srcuxg[ (J  ) * SRCUXG_SIZE_0 + (I-1) ])
/*** srcuxg ***/

/*** srcuya ***/
#define SRCUYA_SIZE_0 (isize+2)
#define SRCUYA_SIZE_1 (jsize+2)
#define SRCUYA(I, J) (srcuya[ (J  ) * SRCUYA_SIZE_0 + (I  ) ])
/*** srcuya ***/

/*** srcuyb ***/
#define SRCUYB_SIZE_0 (isize+2)
#define SRCUYB_SIZE_1 (jsize+2)
#define SRCUYB(I, J) (srcuyb[ (J  ) * SRCUYB_SIZE_0 + (I  ) ])
/*** srcuyb ***/

/*** srcuyg ***/
#define SRCUYG_SIZE_0 (isize+2)
#define SRCUYG_SIZE_1 (jsize+2)
#define SRCUYG(I, J) (srcuyg[ (J  ) * SRCUYG_SIZE_0 + (I  ) ])
/*** srcuyg ***/

/*** srcuza ***/
/*** srcuza ***/

/*** srcuzb ***/
/*** srcuzb ***/

/*** srcuzg ***/
/*** srcuzg ***/

#endif // ARRAYS_{name}_H
