#if !defined(ARRAYS_FLUID_H)
#define ARRAYS_FLUID_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** ux ***/
#if NDIMS == 2
#define UX_SIZE_0 (isize+1)
#define UX_SIZE_1 (jsize+2)
#define UX(I, J) (ux[ (J  ) * UX_SIZE_0 + (I-1) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define UX_SIZE_0 (isize+1)
#define UX_SIZE_1 (jsize+2)
#define UX_SIZE_2 (ksize+2)
#define UX(I, J, K) (ux[ (K  ) * UX_SIZE_1 * UX_SIZE_0 + (J  ) * UX_SIZE_0 + (I-1) ])
#endif // NDIMS == 3
/*** ux ***/

/*** uy ***/
#if NDIMS == 2
#define UY_SIZE_0 (isize+2)
#define UY_SIZE_1 (jsize+2)
#define UY(I, J) (uy[ (J  ) * UY_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define UY_SIZE_0 (isize+2)
#define UY_SIZE_1 (jsize+2)
#define UY_SIZE_2 (ksize+2)
#define UY(I, J, K) (uy[ (K  ) * UY_SIZE_1 * UY_SIZE_0 + (J  ) * UY_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** uy ***/

/*** uz ***/
#if NDIMS == 3
#define UZ_SIZE_0 (isize+2)
#define UZ_SIZE_1 (jsize+2)
#define UZ_SIZE_2 (ksize+2)
#define UZ(I, J, K) (uz[ (K  ) * UZ_SIZE_1 * UZ_SIZE_0 + (J  ) * UZ_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** uz ***/

/*** p ***/
#if NDIMS == 2
#define P_SIZE_0 (isize+2)
#define P_SIZE_1 (jsize+2)
#define P(I, J) (p[ (J  ) * P_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define P_SIZE_0 (isize+2)
#define P_SIZE_1 (jsize+2)
#define P_SIZE_2 (ksize+2)
#define P(I, J, K) (p[ (K  ) * P_SIZE_1 * P_SIZE_0 + (J  ) * P_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** p ***/

/*** psi ***/
#if NDIMS == 2
#define PSI_SIZE_0 (isize+2)
#define PSI_SIZE_1 (jsize+2)
#define PSI(I, J) (psi[ (J  ) * PSI_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define PSI_SIZE_0 (isize+2)
#define PSI_SIZE_1 (jsize+2)
#define PSI_SIZE_2 (ksize+2)
#define PSI(I, J, K) (psi[ (K  ) * PSI_SIZE_1 * PSI_SIZE_0 + (J  ) * PSI_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** psi ***/

/*** srcuxa ***/
#if NDIMS == 2
#define SRCUXA_SIZE_0 (isize+1)
#define SRCUXA_SIZE_1 (jsize+2)
#define SRCUXA(I, J) (srcuxa[ (J  ) * SRCUXA_SIZE_0 + (I-1) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUXA_SIZE_0 (isize+1)
#define SRCUXA_SIZE_1 (jsize+2)
#define SRCUXA_SIZE_2 (ksize+2)
#define SRCUXA(I, J, K) (srcuxa[ (K  ) * SRCUXA_SIZE_1 * SRCUXA_SIZE_0 + (J  ) * SRCUXA_SIZE_0 + (I-1) ])
#endif // NDIMS == 3
/*** srcuxa ***/

/*** srcuxb ***/
#if NDIMS == 2
#define SRCUXB_SIZE_0 (isize+1)
#define SRCUXB_SIZE_1 (jsize+2)
#define SRCUXB(I, J) (srcuxb[ (J  ) * SRCUXB_SIZE_0 + (I-1) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUXB_SIZE_0 (isize+1)
#define SRCUXB_SIZE_1 (jsize+2)
#define SRCUXB_SIZE_2 (ksize+2)
#define SRCUXB(I, J, K) (srcuxb[ (K  ) * SRCUXB_SIZE_1 * SRCUXB_SIZE_0 + (J  ) * SRCUXB_SIZE_0 + (I-1) ])
#endif // NDIMS == 3
/*** srcuxb ***/

/*** srcuxg ***/
#if NDIMS == 2
#define SRCUXG_SIZE_0 (isize+1)
#define SRCUXG_SIZE_1 (jsize+2)
#define SRCUXG(I, J) (srcuxg[ (J  ) * SRCUXG_SIZE_0 + (I-1) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUXG_SIZE_0 (isize+1)
#define SRCUXG_SIZE_1 (jsize+2)
#define SRCUXG_SIZE_2 (ksize+2)
#define SRCUXG(I, J, K) (srcuxg[ (K  ) * SRCUXG_SIZE_1 * SRCUXG_SIZE_0 + (J  ) * SRCUXG_SIZE_0 + (I-1) ])
#endif // NDIMS == 3
/*** srcuxg ***/

/*** srcuya ***/
#if NDIMS == 2
#define SRCUYA_SIZE_0 (isize+2)
#define SRCUYA_SIZE_1 (jsize+2)
#define SRCUYA(I, J) (srcuya[ (J  ) * SRCUYA_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUYA_SIZE_0 (isize+2)
#define SRCUYA_SIZE_1 (jsize+2)
#define SRCUYA_SIZE_2 (ksize+2)
#define SRCUYA(I, J, K) (srcuya[ (K  ) * SRCUYA_SIZE_1 * SRCUYA_SIZE_0 + (J  ) * SRCUYA_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuya ***/

/*** srcuyb ***/
#if NDIMS == 2
#define SRCUYB_SIZE_0 (isize+2)
#define SRCUYB_SIZE_1 (jsize+2)
#define SRCUYB(I, J) (srcuyb[ (J  ) * SRCUYB_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUYB_SIZE_0 (isize+2)
#define SRCUYB_SIZE_1 (jsize+2)
#define SRCUYB_SIZE_2 (ksize+2)
#define SRCUYB(I, J, K) (srcuyb[ (K  ) * SRCUYB_SIZE_1 * SRCUYB_SIZE_0 + (J  ) * SRCUYB_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuyb ***/

/*** srcuyg ***/
#if NDIMS == 2
#define SRCUYG_SIZE_0 (isize+2)
#define SRCUYG_SIZE_1 (jsize+2)
#define SRCUYG(I, J) (srcuyg[ (J  ) * SRCUYG_SIZE_0 + (I  ) ])
#endif // NDIMS == 2
#if NDIMS == 3
#define SRCUYG_SIZE_0 (isize+2)
#define SRCUYG_SIZE_1 (jsize+2)
#define SRCUYG_SIZE_2 (ksize+2)
#define SRCUYG(I, J, K) (srcuyg[ (K  ) * SRCUYG_SIZE_1 * SRCUYG_SIZE_0 + (J  ) * SRCUYG_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuyg ***/

/*** srcuza ***/
#if NDIMS == 3
#define SRCUZA_SIZE_0 (isize+2)
#define SRCUZA_SIZE_1 (jsize+2)
#define SRCUZA_SIZE_2 (ksize+2)
#define SRCUZA(I, J, K) (srcuza[ (K  ) * SRCUZA_SIZE_1 * SRCUZA_SIZE_0 + (J  ) * SRCUZA_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuza ***/

/*** srcuzb ***/
#if NDIMS == 3
#define SRCUZB_SIZE_0 (isize+2)
#define SRCUZB_SIZE_1 (jsize+2)
#define SRCUZB_SIZE_2 (ksize+2)
#define SRCUZB(I, J, K) (srcuzb[ (K  ) * SRCUZB_SIZE_1 * SRCUZB_SIZE_0 + (J  ) * SRCUZB_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuzb ***/

/*** srcuzg ***/
#if NDIMS == 3
#define SRCUZG_SIZE_0 (isize+2)
#define SRCUZG_SIZE_1 (jsize+2)
#define SRCUZG_SIZE_2 (ksize+2)
#define SRCUZG(I, J, K) (srcuzg[ (K  ) * SRCUZG_SIZE_1 * SRCUZG_SIZE_0 + (J  ) * SRCUZG_SIZE_0 + (I  ) ])
#endif // NDIMS == 3
/*** srcuzg ***/

#endif // ARRAYS_{name}_H
