#if !defined(ARRAYS_IB_H)
#define ARRAYS_IB_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** dux ***/
#define DUX_SIZE_0 (isize+2)
#define DUX_SIZE_1 (jsize+2)
#define DUX(I, J) (dux[ (J  ) * DUX_SIZE_0 + (I  ) ])
/*** dux ***/

/*** duy ***/
#define DUY_SIZE_0 (isize+2)
#define DUY_SIZE_1 (jsize+2)
#define DUY(I, J) (duy[ (J  ) * DUY_SIZE_0 + (I  ) ])
/*** duy ***/

/*** duz ***/
/*** duz ***/

#endif // ARRAYS_{name}_H
