#if !defined(ARRAYS_STATISTICS_H)
#define ARRAYS_STATISTICS_H

/* This file is automatically generated by define_array.py */

// check NDIMS (number of spatial dimensions)
#if !defined(NDIMS)
#error "define NDIMS: -DNDIMS=2 or -DNDIMS=3"
#endif

#include "domain.h"

/*** ux1 ***/
#define UX1_SIZE_0 (isize+1)
#define UX1_SIZE_1 (jsize+2)
#define UX1(I, J) (ux1[ (J  ) * UX1_SIZE_0 + (I-1) ])
/*** ux1 ***/

/*** ux2 ***/
#define UX2_SIZE_0 (isize+1)
#define UX2_SIZE_1 (jsize+2)
#define UX2(I, J) (ux2[ (J  ) * UX2_SIZE_0 + (I-1) ])
/*** ux2 ***/

/*** uy1 ***/
#define UY1_SIZE_0 (isize+2)
#define UY1_SIZE_1 (jsize+2)
#define UY1(I, J) (uy1[ (J  ) * UY1_SIZE_0 + (I  ) ])
/*** uy1 ***/

/*** uy2 ***/
#define UY2_SIZE_0 (isize+2)
#define UY2_SIZE_1 (jsize+2)
#define UY2(I, J) (uy2[ (J  ) * UY2_SIZE_0 + (I  ) ])
/*** uy2 ***/

/*** uz1 ***/
/*** uz1 ***/

/*** uz2 ***/
/*** uz2 ***/

/*** temp1 ***/
#define TEMP1_SIZE_0 (isize+2)
#define TEMP1_SIZE_1 (jsize+2)
#define TEMP1(I, J) (temp1[ (J  ) * TEMP1_SIZE_0 + (I  ) ])
/*** temp1 ***/

/*** temp2 ***/
#define TEMP2_SIZE_0 (isize+2)
#define TEMP2_SIZE_1 (jsize+2)
#define TEMP2(I, J) (temp2[ (J  ) * TEMP2_SIZE_0 + (I  ) ])
/*** temp2 ***/

#endif // ARRAYS_{name}_H
